### ISSUE TITLE
Support VS 2017 (RC)

### ISSUE THREAD

**Issue by Abhith** [Elders/VSE-FormatDocumentOnSave#3]

**Comment by mynkow** [comment]
Please check the new version. If it is working for you please close this

**Comment by yannduran** [comment]
The extension didn't successfully install for me. Viewing the log isn't very helpful. There's a ```FileNotFound``` error but it doesn't say which file.

Here's the actual log text:

>27/12/2016 8:13:21 PM - The extension with ID '2f4fac85-be4e-4d7a-8c74-93cc4389b427' is not installed to Microsoft Visual Studio Community 2017 RC.
27/12/2016 8:13:41 PM - The following target products have been selected...
27/12/2016 8:13:41 PM - 	Microsoft Visual Studio Community 2017 RC
27/12/2016 8:13:41 PM - 
27/12/2016 8:13:42 PM - Beginning to install extension to Microsoft Visual Studio Community 2017 RC...
27/12/2016 8:13:42 PM - Install Error : System.IO.FileNotFoundException: Unable to find the specified file.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetCurrentSetupInstance()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by mynkow** [comment]
Can you please send me a screenshot of this folder:

`%localappdata%\Microsoft\VisualStudio\15.0_e7a44a0dExp\Extensions\Elders\Format document on Save\1.14`

https://gyazo.com/090d35d49528d0a437199e951b925bb8

**Comment by Abhith** [comment]
I tried to install and it worked for me.
